name: ManualMending
api-version: '1.16'
version: @version@
main: io.musician101.manualmending.spigot.SpigotManualMending
authors: [Musician101]
description: Improved behavior for the vanilla Mending enchantment.
commands:
  mend:
    aliases: [mend]
  mendReload:
    aliases: [mendReload]
